### PR TITLE
Nested menus

### PR DESCRIPTION
**Pull request by vkushnir**
Hello. No good in english, sorry.
Added nested menu support. No change in ~/.ssh/config reuired. 
Nested menu generated by host names with separators.
Very useful if you have more than 200 hosts.
Sample:
`Host city.region.group.host`
- ciry
  - region
    - group
      - host
      - exit

If you intrested.

### CODE REVIEW

**Comment by LordBurrito** [comment]
Hi @antonjah Thank you so much for your ssh-menu, it's awesome!

Hi @vkushnir Thanks for your update, I was looking exactly for something like that!

I think you should remove from sshmenu.py the line:
`from keyword import`

about the nesting, do you think it's possible to set the "folder" using another logic ?
with your update I can easily manage all my session but that brakes the ssh_config.

example from my ssh_config:
```
### Amsterdam
Host OpenStack.Amsterdam.AM-SV-INFR01
     HostName xx.xx.x.x
     User ubuntu
```
 in this way I'm not able to ssh into the machine with a simple command anymore and I have to use
`~$ ssh OpenStack.Amsterdam.AM-SV-INFR01`

instead of:
`~$ ssh AM-SV-INFR01`

I'm not able to code in python but an idea could be to read the path from the comments of the ssh_config .

Example:
```
**### OpenStack.Amsterdam**
Host AM-SV-INFR01
     HostName xx.xx.x.x
     User ubuntu
```
in this way we can have both of the convenience of ssh_config and your ssh-menu.

Thanks for reading,
Davide

**Comment by antonjah** [comment]
I completely forgot about this "project".
I'll take a look at the pull request tomorrow :-)

**Comment by LordBurrito** [comment]
Thanks a lot, much appreciated!

**Comment by antonjah** [comment]
Ok so I've looked this over and I've decided to add the Tmux support. It's now added in the latest version (2.0.4).
I have decided not to add the custom parsing of a nested configuration file. I like the idea but not the implementation.

I will close the this PR and look for a different solution to a nested config.

Changes:
https://github.com/antonjah/ssh-menu/compare/86dd4be6fb63a040cc0de4bd6301bcda27e8f1fd...a83eb8f5c03296e57069e056fb41d22048cc5017

**Comment by antonjah** [comment]
Also, huge thanks @vkushnir for the added functionality. I have added a contribution section in the README.

**Pull request closed without merging**
